### ISSUE TITLE
Build fails on dev branch

### ISSUE THREAD

**Issue by MicrowaveDev** [cybercongress/cyb-archeology#246]
### Current Behavior
Build fails on dev branch, [0dfb5](https://github.com/cybercongress/cyb/tree/0dfb5e6f24d135b2b0f9129dbec243ae5639a101) commit

### Log
```
yarn run v1.6.0
(node:11677) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ rimraf dist && yarn run build && electron-builder --config electron/config.json
(node:11680) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ rimraf build && webpack --mode production --config webpack/webpack.config && yarn run build:preload
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
Hash: b20de421e1a48614a501
Version: webpack 4.25.0
Time: 40928ms
Built at: 2019-06-13 17:08:04
                                     Asset       Size  Chunks                    Chunk Names
bell-ring-voice-alarm-clock.9970b9078e.svg  682 bytes          [emitted]         
                    cyb-red.c21ed70080.png   32.1 KiB          [emitted]         
                    cybEye2.2da7bf8f59.png   26.1 KiB          [emitted]         
              cyb_animation.0849524ee0.gif   1.04 MiB          [emitted]  [big]  
                   cyb_init.d733fe2423.png   26.3 KiB          [emitted]         
                               electron.js   3.32 KiB          [emitted]         
                        eye.fd1a1ba6e2.jpg   20.1 KiB          [emitted]         
                               favicon.ico   3.78 KiB          [emitted]         
                   favorite.71132d6de3.svg  408 bytes          [emitted]         
            favourites_link.a4111cd272.png   10.8 KiB          [emitted]         
            favourites_name.1c3272cd42.png   7.46 KiB          [emitted]         
                       hash.584ccf2d14.png   15.7 KiB          [emitted]         
                    history.1707334389.svg  543 bytes          [emitted]         
    ic-account-circle-48-px.a25e98e07b.svg  458 bytes          [emitted]         
                    idrobot.fd1e4c5f85.png   70.9 KiB          [emitted]         
                                index.html  911 bytes          [emitted]         
                   ipfs_add.486e0ff1fb.png   50.9 KiB          [emitted]         
               ipfs_connect.cfe16bb9e2.png    112 KiB          [emitted]         
                  ipfs_link.3f0a1a935f.png   23.4 KiB          [emitted]         
               ipfs_welcome.105e87bc24.png   35.1 KiB          [emitted]         
                       logo.934cc89a35.svg   3.68 KiB          [emitted]         
                 main.bundle.b20de421e1.js   24.8 MiB       0  [emitted]  [big]  main
           non-zero-balance.9b8f5fd0db.png   86.2 KiB          [emitted]         
                  npm_start.52b644fbae.png    124 KiB          [emitted]         
                open-search.33b373303c.png    451 KiB          [emitted]  [big]  
                  open_done.4121812164.png   1020 KiB          [emitted]  [big]  
                    par_add.8c558c657d.png    111 KiB          [emitted]         
                   par_sync.26a6b2433d.png   1.12 MiB          [emitted]  [big]  
                 par_synced.998c19d00c.png    664 KiB          [emitted]  [big]  
              search-Berlin.153919ee97.png    173 KiB          [emitted]         
         search-link-result.25ea4ecfe9.png    115 KiB          [emitted]         
                search-link.b5a75aff76.png    478 KiB          [emitted]  [big]  
                   settings.102d6d8f87.svg   1.69 KiB          [emitted]         
              settings_ipfs.2ab8e4ec02.png    278 KiB          [emitted]  [big]  
            settings_switch.0554901c73.png   55.4 KiB          [emitted]         
                trash-focus.9b2777ab26.svg   1.06 KiB          [emitted]         
                      trash.11cdb9fe5e.svg   1.06 KiB          [emitted]         
                     wallet.591b4310f3.svg  754 bytes          [emitted]         
Entrypoint main [big] = main.bundle.b20de421e1.js
  [12] ../node_modules/react-router/es/index.js + 32 modules 74.5 KiB {0} [built]
       |    33 modules
  [18] ./redux/settings.js 7.28 KiB {0} [built]
  [19] ./utils.js 5.05 KiB {0} [built]
  [21] ./redux/wallet.js 29.6 KiB {0} [built]
  [26] ./redux/browser.js 6.62 KiB {0} [built]
  [30] ./redux/appMenu.js 3.43 KiB {0} [built]
  [35] ./redux/cyber.js 5.22 KiB {0} [built]
  [46] ./redux/rootRegistry.js 2.82 KiB {0} [built]
  [57] ./redux/signer.js 1.12 KiB {0} [built]
  [74] ./redux/intro.jsx 588 bytes {0} [built]
 [180] ./cyber/Cyber.js 10.3 KiB {0} [built]
[1251] ./preload/zero.js 4.52 KiB {0} [built]
[1374] ./index.css 1.05 KiB {0} [built]
[1375] ../node_modules/css-loader!./index.css 818 bytes {0} [built]
[1376] ./index.js + 77 modules 198 KiB {0} [built]
       | ./index.js 659 bytes [built]
       | ./redux/store.js 1.18 KiB [built]
       | ./router.jsx 2.75 KiB [built]
       | ./containers/Application/Application.jsx 3.27 KiB [built]
       | ./containers/RootRegistry/RootRegistry.jsx 6.49 KiB [built]
       | ./containers/Settings/Settings.jsx 1.78 KiB [built]
       | ./containers/Wallet/Wallet.jsx 2.63 KiB [built]
       | ./containers/NotFound/NotFound.jsx 1.38 KiB [built]
       | ./containers/Browser/Browser.jsx 3.14 KiB [built]
       | ./containers/Home/index.jsx 1.45 KiB [built]
       | ./containers/TransactionView/TransactionView.jsx 1.06 KiB [built]
       | ./containers/History/History.jsx 2.74 KiB [built]
       | ./containers/TxQueue/TxQueue.jsx 6.63 KiB [built]
       | ./containers/Help/HelpHome.jsx 1.99 KiB [built]
       | ./containers/Help/Create.jsx 2.93 KiB [built]
       |     + 63 hidden modules
    + 1362 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  cyb_animation.0849524ee0.gif (1.04 MiB)
  open_done.4121812164.png (1020 KiB)
  settings_ipfs.2ab8e4ec02.png (278 KiB)
  par_sync.26a6b2433d.png (1.12 MiB)
  par_synced.998c19d00c.png (664 KiB)
  open-search.33b373303c.png (451 KiB)
  search-link.b5a75aff76.png (478 KiB)
  main.bundle.b20de421e1.js (24.8 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (24.8 MiB)
      main.bundle.b20de421e1.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ../node_modules/html-webpack-plugin/lib/loader.js!../public/index.html 1010 bytes {0} [built]
        + 3 hidden modules
(node:11688) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ webpack --mode production --config webpack/preload
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
Hash: 0d0818209811ba49f814
Version: webpack 4.25.0
Time: 1280ms
Built at: 2019-06-13 17:08:07
     Asset      Size  Chunks             Chunk Names
preload.js  6.45 KiB       0  [emitted]  main
Entrypoint main = preload.js
[0] ./preload.js 4.76 KiB {0} [built]
[1] external "electron" 42 bytes {0} [built]
[2] ./preload/EventEmitter.js 9.43 KiB {0} [built]
  • electron-builder version=20.28.4
  • loaded configuration file=/Users/jonybang/workspace/cyb/electron/config.json
  • loaded parent configuration preset=react-cra
  • Specified application directory equals to project dir — superfluous or wrong configuration appDirectory=.
  • writing effective config file=dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
  • rebuilding native dependency name=fsevents
  • rebuilding native dependency name=keccak
  • rebuilding native dependency name=websocket
  • rebuilding native dependency name=ursa-optional
  • rebuilding native dependency name=sha3
  • rebuilding native dependency name=secp256k1
  • rebuilding native dependency name=scrypt
  • packaging       platform=darwin arch=x64 electron=3.0.2 appOutDir=dist/mac
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1072ee7]

goroutine 211 [running]:
syscall.ByteSliceFromString(0x0, 0x23, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.3/libexec/src/syscall/syscall.go:52 +0x37
syscall.BytePtrFromString(0x0, 0x23, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.3/libexec/src/syscall/syscall.go:72 +0x35
syscall.Symlink(0x0, 0x23, 0xc420332000, 0x77, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.3/libexec/src/syscall/zsyscall_darwin_amd64.go:1218 +0x3c
os.Symlink(0x0, 0x23, 0xc420332000, 0x77, 0x0, 0xc420040000)
	/usr/local/Cellar/go/1.10.3/libexec/src/os/file_unix.go:332 +0x4d
github.com/develar/app-builder/pkg/fs.CreateLinks.func1.1(0x0, 0xc4200922a0)
	/Users/develar/go/src/github.com/develar/app-builder/pkg/fs/copier.go:88 +0x45
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2(0xc42000c400, 0xc4200922a0, 0xc420328060, 0xc42029e0f0)
	/Users/develar/go/src/github.com/develar/app-builder/pkg/util/async.go:67 +0x69
created by github.com/develar/app-builder/pkg/util.MapAsyncConcurrency
	/Users/develar/go/src/github.com/develar/app-builder/pkg/util/async.go:57 +0x2ee
Error: /Users/jonybang/workspace/cyb/node_modules/app-builder-bin/mac/app-builder exited with code 2
    at ChildProcess.childProcess.once.code (/Users/jonybang/workspace/cyb/node_modules/builder-util/src/util.ts:254:14)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
From previous event:
    at unpack (/Users/jonybang/workspace/cyb/node_modules/app-builder-lib/out/electron/ElectronFramework.js:191:18)
    at Object.prepareApplicationStageDirectory (/Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:148:50)
    at /Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/platformPackager.ts:179:21
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.doPack (/Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/platformPackager.ts:166:165)
    at /Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/jonybang/workspace/cyb/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/jonybang/workspace/cyb/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Packager.doBuild (/Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /Users/jonybang/workspace/cyb/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/jonybang/workspace/cyb/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at Packager._build (/Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/Users/jonybang/workspace/cyb/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/Users/jonybang/workspace/cyb/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/jonybang/workspace/cyb/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Object.args [as handler] (/Users/jonybang/workspace/cyb/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (/Users/jonybang/workspace/cyb/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/jonybang/workspace/cyb/node_modules/yargs/yargs.js:1085:24)
    at Object.get [as argv] (/Users/jonybang/workspace/cyb/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/Users/jonybang/workspace/cyb/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior
Successful build

### Reproduction
1. clone repo
2. run commands
```
yarn
yarn run release
```

### Additional Information
Node version: v10.15.3
OS: MacOS High Sierra 10.13.6

**Comment by sebastiantf** [comment]
Did you try building with Node `v8.12`?

I ran into issues while building with v12. I used nvm to use v8.12 as I found the version specified in `.travis.yml` as:

`node_js: "8.12"`

**Comment by mastercyb** [comment]
Dublicate of #250
